# Generated by Django 4.2.7 on 2023-11-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=300)),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'direcciones',
                'managed': False,
            },
        ),
    ]
