# Generated by Django 4.2.7 on 2023-11-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=250)),
                ('nombre_medicamento', models.CharField(max_length=150)),
                ('desc_medicamento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=33)),
            ],
            options={
                'db_table': 'medicamentos',
                'managed': False,
            },
        ),
    ]
