# Generated by Django 4.2.7 on 2023-11-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0002_alter_medicamento_desc_medicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='desc_medicamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
