# Generated by Django 4.2.6 on 2023-11-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0003_alter_medicamento_desc_medicamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamento',
            options={'managed': False},
        ),
    ]
