# Generated by Django 4.2.6 on 2023-11-08 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0004_alter_medicamento_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicamento',
            table='medicamentos',
        ),
    ]
